TakenAt: 2019-01-15T11:39:29Z
TakenAtLocal: 2019-01-15T11:39:29Z
TakenSrc: meta
UID: psrtkjhi4xsz7mki
Type: image
Title: Biomechanics Course Image
OriginalName: biomechanics-course-image-002-1
Year: 2019
Month: 1
Day: 15
Quality: 3
Details:
  Keywords: biomechanics, course, green
  Software: Windows Photo Editor 10.0.10011.16384
  SoftwareSrc: meta
CreatedBy: usrtki6ll4f1qxcr
CreatedAt: 2025-02-17T08:50:05Z
UpdatedAt: 2025-02-17T08:50:09Z
EditedAt: 2025-02-17T08:50:09Z
