name: Build Environment-Unit Tests & CheckStyle
#
#on:
#  push:
#    branches:
#      - feature/my_feature  # Adjust to the branches you want to trigger on
#  workflow_dispatch:  # Allows manual execution



jobs:
  lint:
    name: Run Go Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install libvips (Required for govips)
        run: sudo apt-get update && sudo apt-get install -y libvips-dev

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.5
          args: --timeout=5m --max-issues-per-linter=0 --max-same-issues=0 || true

  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JavaScript Dependencies
        run: cd frontend && npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx || true
        continue-on-error: true

  Build_Push_Docker_Image_Run_Unit_Tests:
    runs-on: ubuntu-latest
    needs: eslint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js for JavaScript/TypeScript tests
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JavaScript Dependencies
        run: cd frontend && npm install

      - name: Install Karma CLI
        run: npm install -g karma-cli

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Run JavaScript Unit Tests
        run: make test-js
        continue-on-error: true

      - name: Build Docker Image
        run: docker build -t ahmadnas/photoprism-app -f ahmad.dockerfile .

      - name: Push Docker Image to DockerHub
        run: docker push ahmadnas/photoprism-app

