name: Build and Run Environment Tests

on:
  push:
    branches:
      - feature/my_feature
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make chromium-browser
          npm install  # Ensure dependencies are installed

      - name: Ensure storage directory exists
        run: |
          mkdir -p storage
          cd storage
          wget -c https://dl.photoprism.app/qa/acceptance.tar.gz -O - | tar -xz

      - name: Run only authentication and sharing tests
        run: |
          make acceptance-run-chromium TESTS='--test-meta "testID=authentication-001" --test-meta "testID=sharing-001"'
