name: Run Java Smoke Tests for PhotoPrism

on:
  workflow_dispatch:  # Allows manual execution
  push:
    branches:
      - feature/my_feature



jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Java test repository
        uses: actions/checkout@v4
        with:
          repository: ahmadnas00/PhotoprismProject
          path: photoprism-tests

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: photoprism-tests
          path: photoprism-tests


  TestChrome_131_0:
    name: UI Tests - Chrome 131.0
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download test repository
        uses: actions/download-artifact@v4
        with:
          name: photoprism-tests
          path: photoprism-tests

      - name: Pull and Run PhotoPrism Docker Container
        run: |
          docker pull ahmadnas/photoprism-app
          docker run -d --name ahmad-photoprism \
            -v "$(pwd)/storage/originals:/photoprism/originals" \
            -p 2342:2342 ahmadnas/photoprism-app

      - name: Wait for PhotoPrism to be accessible
        run: |
          for i in {1..30}; do
            curl --silent --fail http://localhost:2342 && break
            echo "Waiting for PhotoPrism..."
            sleep 2
          done

      - name: Launch standalone grid - Chrome
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:latest

      - name: Run Chrome UI Tests
        run: |
          cd photoprism-tests
          export BROWSER=chrome
          export GRID_URL=http://localhost:4444
          export BASE_URL=$BASE_URL
          mvn clean test -Dtest=TestAutomationProjectTesting.SmokeTests

      - name: Tear down containers
        if: always()
        run: |
          docker stop grid_container || true
          docker rm grid_container || true
          docker stop ahmad-photoprism || true
          docker rm ahmad-photoprism || true

  TestAPI:
    name: API Tests
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      checks: write
      contents: read

    steps:
      - name: Download test repository
        uses: actions/download-artifact@v4
        with:
          name: photoprism-tests
          path: photoprism-tests

      - name: Pull and Run PhotoPrism Docker Container
        run: |
          docker pull ahmadnas/photoprism-app
          docker run -d --name ahmad-photoprism \
            -v "$(pwd)/storage/originals:/photoprism/originals" \
            -p 2342:2342 ahmadnas/photoprism-app

      - name: Wait for PhotoPrism to be accessible
        run: |
          for i in {1..30}; do
            curl --silent --fail http://localhost:2342 && break
            echo "Waiting for PhotoPrism..."
            sleep 2
          done

      - name: Launch standalone grid - Chrome (for API tests)
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:latest

#      - name: Checkout Code
#        uses: actions/checkout@v4

      - name: Run API Tests
        run: |
          cd photoprism-tests
          export BROWSER=chrome
          export GRID_URL=http://localhost:4444
          export BASE_URL=http://localhost:2342
          mvn clean test -Dtest=TestAutomationProjectTesting.ApiTest

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

      - name: Tear down containers
        if: always()
        run: |
          docker stop grid_container || true
          docker rm grid_container || true
          docker stop ahmad-photoprism || true
          docker rm ahmad-photoprism || true


